import Testing
@testable import Day07

let exampleInput =
"""
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

@Suite struct `to get the first star on day 07` {
    @Test func `the total number of splits in for the example input should be 21`() {
        #expect(splitCount(in: exampleInput) == 21)
    }
    
    @Test func `the total number of splits in for the actual input should be 1660`() {
        #expect(splitCount(in: input) == 1660)
    }
}

@Suite struct `to get the second star on day 08` {
    @Test func `the total number of paths in for the example input should be 21`() {
        #expect(pathCount(in: exampleInput) == 40)
    }
    
    @Test func `the total number of paths in for be 2`() {
        let input =
        """
        .S.
        ...
        .^.
        ...
        """
        #expect(pathCount(in: input) == 2)
    }
    
    @Test func `the total number of paths in for be 4`() {
        let input =
        """
        ..S..
        .....
        ..^..
        .....
        .^.^.
        .....
        """
        #expect(pathCount(in: input) == 4)
    }
    
    @Test func `the total number of paths in for be 7`() {
        let input =
        """
        ...S..
        ......
        ...^..
        ......
        ..^...
        ......
        .^.^..
        ......
        ....^.
        ......
        """
        #expect(pathCount(in: input) == 7)
    }
    
    @Test func `the total number of paths in for the actual input should be 305999729392659`() {
        #expect(pathCount(in: input) == 305999729392659)
    }
}
