import Testing
@testable import Day07

let exampleInput =
"""
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

@Suite struct `to get the first star on day 07` {
    @Test func `the total number of splits in for the example input should be 21`() {
        #expect(splitCount(in: exampleInput) == 21)
    }
}

@Test func example() async throws {
    // Write your test here and use APIs like `#expect(...)` to check expected conditions.
}
